version: "3"
services:
 postgres:
    image: "postgres:alpine3.18"
    command: postgres -c 'max_connections=200'
    ports:
      - "5432:5432"
      - "5433:5433"
    environment:
      - POSTGRES_PASS=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - 'postgres_data:/pgdata'

volumes:
  postgres_data:
